[package]
name = "rCrawly"
version = "0.1.0"
authors = ["Lorenzo <lorenzofersteam@live.it>"]

[dependencies]
select = "0.4.0"
hyper = "0.10.10"
hyper-rustls = "0.6.0"
#TODO Switch from select to use directly html5ever

